# Generated by Django 3.1.7 on 2021-03-19 18:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20210319_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 19, 18, 23, 21, 383396, tzinfo=utc)),
        ),
    ]
